from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

DATA_ROOT = REPO_ROOT / "data"
CANONICAL_DATA_FILE = DATA_ROOT / "kmetbench.json"
ARTIFACTS_ROOT = DATA_ROOT / "artifacts"
CATEGORY_ARTIFACTS_ROOT = ARTIFACTS_ROOT / "category"
KOREAN_REGIONALITY_ARTIFACTS_ROOT = ARTIFACTS_ROOT / "korean_regionality_data"
STANDARDS_ARTIFACTS_ROOT = ARTIFACTS_ROOT / "standards"
SURVEY_ARTIFACTS_ROOT = ARTIFACTS_ROOT / "survey"
MERGED_DATA_ROOT = DATA_ROOT / "merged"
IMAGE_ROOT = DATA_ROOT / "shuffled"

CONFIGS_ROOT = REPO_ROOT / "configs"
MODEL_CONFIG_ROOT = CONFIGS_ROOT / "models"

RESULTS_ROOT = REPO_ROOT / "results"
PRIVATE_RESULTS_ROOT = RESULTS_ROOT
EVALUATION_RESULTS_ROOT = RESULTS_ROOT / "evaluation"
ANALYSIS_RESULTS_ROOT = RESULTS_ROOT / "analysis"
PUBLIC_SUMMARY_ROOT = RESULTS_ROOT / "public_summary"
PRIVATE_SUMMARY_ROOT = RESULTS_ROOT / "private_summary"
PREPROCESS_PRIVATE_SUMMARY_ROOT = PRIVATE_SUMMARY_ROOT / "preprocess"
EVALUATION_INDEX_ROOT = PRIVATE_SUMMARY_ROOT / "evaluation_indexes"
MANIFESTS_ROOT = RESULTS_ROOT / "manifests"

PREPROCESS_ARCHIVE_ROOT = DATA_ROOT / "archive"
ARCHIVED_MERGED_DATA_ROOT = PREPROCESS_ARCHIVE_ROOT

SCRIPTS_ROOT = REPO_ROOT / "scripts"
SRC_ROOT = REPO_ROOT / "src"
TESTS_ROOT = REPO_ROOT / "tests"
