metadata:
  release_date: null
  model_size: null
  context_window: null
  max_output_tokens: null
  modality: "llm"
  is_reasoning: false
  huggingface_url: ""

model:
  name: "model-name"
  client: "openai"
  engine: "vllm"
  base_url: "http://127.0.0.1:8237/v1"
  api_key_env: "EMPTY"
  is_vlm: false
  params:
    max_tokens: null
    temperature: null
    top_p: 0.95

prompt_overrides:
  advanced:
    temperature: 0.1
  reasoning:
    temperature: 1.0

vllm:
  gpu_memory_utilization: 0.9
  visible_devices: "0"
  tensor_parallel_size: 1
  port: 8237
  host: "0.0.0.0"
  max_model_len: 8192
  max_num_seqs: 4
  image_limit: 4
  trust_remote_code: true
