metadata:
  release_date: null
  model_size: 2
  context_window: null
  max_output_tokens: null
  modality: "vlm"
  is_reasoning: true
  huggingface_url: "https://huggingface.co/OpenGVLab/InternVL3_5-2B-Instruct"

model:
  name: "OpenGVLab/InternVL3_5-2B-Instruct"
  client: "openai"
  engine: "vllm"
  base_url: "http://127.0.0.1:8251/v1"
  api_key_env: "EMPTY"
  is_vlm: true
  params:
    max_tokens: null
    temperature: null
    top_p: 0.95

prompt_overrides:
  advanced:
    temperature: 0.1
  reasoning:
    temperature: 1.0

vllm:
  gpu_memory_utilization: 0.95
  visible_devices: "0"
  port: 8251
  host: "0.0.0.0"
  max_model_len: 16384
  tensor_parallel_size: 1
