from __future__ import annotations

MODEL_ORDER = (
    "skt/A.X-4.0",
    "skt/A.X-4.0-Light",
    "skt/A.X-4.0-VL-Light",
    "LGAI-EXAONE/EXAONE-4.0-1.2B",
    "LGAI-EXAONE/EXAONE-4.0-32B",
    "LGAI-EXAONE/EXAONE-4.5-33B",
    "NCSOFT/VARCO-VISION-2.0-1.7B",
    "NCSOFT/VARCO-VISION-2.0-14B",
    "naver-hyperclovax/HyperCLOVAX-SEED-Think-14B",
    "naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B",
    "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B",
    "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B",
    "openai/gpt-oss-20b",
    "openai/gpt-oss-120b",
    "meta-llama/Llama-3.2-90B-Vision-Instruct",
    "meta-llama/Llama-3.2-1B-Instruct",
    "meta-llama/Llama-3.2-3B-Instruct",
    "meta-llama/Llama-3.1-8B-Instruct",
    "meta-llama/Llama-3.1-70B-Instruct",
    "microsoft/Phi-4",
    "microsoft/Phi-4-reasoning",
    "microsoft/Phi-4-mini-instruct",
    "microsoft/Phi-4-mini-reasoning",
    "Qwen/Qwen3-VL-235B-A22B-Instruct",
    "Qwen/Qwen3-VL-235B-A22B-Thinking",
    "Qwen/Qwen3-VL-30B-A3B-Instruct",
    "Qwen/Qwen3-VL-30B-A3B-Thinking",
    "Qwen/Qwen3-VL-32B-Instruct",
    "Qwen/Qwen3-VL-32B-Thinking",
    "Qwen/Qwen3-VL-8B-Thinking",
    "Qwen/Qwen3-VL-8B-Instruct",
    "Qwen/Qwen3-VL-4B-Instruct",
    "Qwen/Qwen3-VL-4B-Thinking",
    "Qwen/Qwen3-30B-A3B-Thinking-2507",
    "Qwen/Qwen3-30B-A3B-Instruct-2507",
    "Qwen/Qwen3-4B-Thinking-2507",
    "Qwen/Qwen3-4B-Instruct-2507",
    "Qwen/Qwen3-0.6B",
    "Qwen/Qwen3-1.7B",
    "Qwen/Qwen3-4B",
    "Qwen/Qwen3-8B",
    "Qwen/Qwen3-14B",
    "Qwen/Qwen3-32B",
    "Qwen/QVQ-72B-Preview",
    "Qwen/Qwen2.5-VL-3B-Instruct",
    "Qwen/Qwen2.5-VL-7B-Instruct",
    "Qwen/Qwen2.5-VL-32B-Instruct",
    "Qwen/Qwen2.5-VL-72B-Instruct",
    "OpenGVLab/InternVL3_5-38B-Instruct",
    "OpenGVLab/InternVL3_5-14B-Instruct",
    "OpenGVLab/InternVL3_5-8B-Instruct",
    "OpenGVLab/InternVL3_5-4B-Instruct",
    "OpenGVLab/InternVL3_5-2B-Instruct",
    "OpenGVLab/InternVL3_5-1B-Instruct",
    "CohereLabs/command-a-reasoning-08-2025",
    "CohereLabs/c4ai-command-a-03-2025",
    "gemini-3-pro-preview",
    "gpt-5.2",
)

MULTIMODAL_MODELS = frozenset(
    {
        "skt/A.X-4.0-VL-Light",
        "NCSOFT/VARCO-VISION-2.0-1.7B",
        "NCSOFT/VARCO-VISION-2.0-14B",
        "LGAI-EXAONE/EXAONE-4.5-33B",
        "naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B",
        "meta-llama/Llama-3.2-90B-Vision-Instruct",
        "Qwen/Qwen3-VL-235B-A22B-Instruct",
        "Qwen/Qwen3-VL-235B-A22B-Thinking",
        "Qwen/Qwen3-VL-30B-A3B-Instruct",
        "Qwen/Qwen3-VL-30B-A3B-Thinking",
        "Qwen/Qwen3-VL-32B-Instruct",
        "Qwen/Qwen3-VL-32B-Thinking",
        "Qwen/Qwen3-VL-8B-Thinking",
        "Qwen/Qwen3-VL-8B-Instruct",
        "Qwen/Qwen3-VL-4B-Instruct",
        "Qwen/Qwen3-VL-4B-Thinking",
        "Qwen/QVQ-72B-Preview",
        "Qwen/Qwen2.5-VL-3B-Instruct",
        "Qwen/Qwen2.5-VL-7B-Instruct",
        "Qwen/Qwen2.5-VL-32B-Instruct",
        "Qwen/Qwen2.5-VL-72B-Instruct",
        "OpenGVLab/InternVL3_5-38B-Instruct",
        "OpenGVLab/InternVL3_5-14B-Instruct",
        "OpenGVLab/InternVL3_5-8B-Instruct",
        "OpenGVLab/InternVL3_5-4B-Instruct",
        "OpenGVLab/InternVL3_5-2B-Instruct",
        "OpenGVLab/InternVL3_5-1B-Instruct",
        "gemini-3-pro-preview",
        "gpt-5.2",
    }
)

REASONING_MODELS = frozenset(
    {
        "naver-hyperclovax/HyperCLOVAX-SEED-Think-14B",
        "LGAI-EXAONE/EXAONE-4.0-1.2B",
        "LGAI-EXAONE/EXAONE-4.0-32B",
        "LGAI-EXAONE/EXAONE-4.5-33B",
        "openai/gpt-oss-20b",
        "openai/gpt-oss-120b",
        "microsoft/Phi-4-reasoning",
        "microsoft/Phi-4-mini-reasoning",
        "Qwen/Qwen3-VL-235B-A22B-Thinking",
        "Qwen/Qwen3-VL-30B-A3B-Thinking",
        "Qwen/Qwen3-30B-A3B-Thinking-2507",
        "Qwen/Qwen3-4B-Thinking-2507",
        "Qwen/Qwen3-0.6B",
        "Qwen/Qwen3-1.7B",
        "Qwen/Qwen3-4B",
        "Qwen/Qwen3-8B",
        "Qwen/Qwen3-VL-32B-Instruct",
        "Qwen/Qwen3-VL-32B-Thinking",
        "Qwen/Qwen3-VL-8B-Thinking",
        "Qwen/Qwen3-VL-8B-Instruct",
        "Qwen/Qwen3-VL-4B-Instruct",
        "Qwen/Qwen3-VL-4B-Thinking",
        "Qwen/Qwen3-14B",
        "Qwen/Qwen3-32B",
        "Qwen/QVQ-72B-Preview",
        "OpenGVLab/InternVL3_5-38B-Instruct",
        "OpenGVLab/InternVL3_5-14B-Instruct",
        "OpenGVLab/InternVL3_5-8B-Instruct",
        "OpenGVLab/InternVL3_5-4B-Instruct",
        "OpenGVLab/InternVL3_5-2B-Instruct",
        "OpenGVLab/InternVL3_5-1B-Instruct",
        "CohereLabs/command-a-reasoning-08-2025",
        "gemini-3-pro-preview",
        "gpt-5.2",
    }
)

KOREAN_MODELS = frozenset(
    {
        "skt/A.X-4.0",
        "skt/A.X-4.0-Light",
        "skt/A.X-4.0-VL-Light",
        "LGAI-EXAONE/EXAONE-4.0-1.2B",
        "LGAI-EXAONE/EXAONE-4.0-32B",
        "LGAI-EXAONE/EXAONE-4.5-33B",
        "NCSOFT/VARCO-VISION-2.0-1.7B",
        "NCSOFT/VARCO-VISION-2.0-14B",
        "naver-hyperclovax/HyperCLOVAX-SEED-Think-14B",
        "naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B",
        "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B",
        "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B",
    }
)

PROPRIETARY_MODELS = frozenset({"gemini-3-pro-preview", "gpt-5.2"})

MODEL_SIZE_MAP = {
    "skt/A.X-4.0": 72,
    "skt/A.X-4.0-Light": 7,
    "skt/A.X-4.0-VL-Light": 8,
    "LGAI-EXAONE/EXAONE-4.0-1.2B": 1.2,
    "LGAI-EXAONE/EXAONE-4.0-32B": 32,
    "LGAI-EXAONE/EXAONE-4.5-33B": 33,
    "NCSOFT/VARCO-VISION-2.0-1.7B": 1.7,
    "NCSOFT/VARCO-VISION-2.0-14B": 14,
    "naver-hyperclovax/HyperCLOVAX-SEED-Think-14B": 15,
    "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B": 1.5,
    "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B": 0.5,
    "naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B": 3,
    "openai/gpt-oss-20b": 20,
    "openai/gpt-oss-120b": 120,
    "meta-llama/Llama-3.2-90B-Vision-Instruct": 88,
    "meta-llama/Llama-3.2-1B-Instruct": 1,
    "meta-llama/Llama-3.2-3B-Instruct": 3,
    "meta-llama/Llama-3.1-8B-Instruct": 8,
    "meta-llama/Llama-3.1-70B-Instruct": 71,
    "microsoft/Phi-4": 15,
    "microsoft/Phi-4-reasoning": 15,
    "microsoft/Phi-4-mini-reasoning": 4,
    "microsoft/Phi-4-mini-instruct": 4,
    "Qwen/Qwen3-VL-235B-A22B-Instruct": 235,
    "Qwen/Qwen3-VL-235B-A22B-Thinking": 235,
    "Qwen/Qwen3-VL-32B-Instruct": 32,
    "Qwen/Qwen3-VL-30B-A3B-Thinking": 31,
    "Qwen/Qwen3-VL-30B-A3B-Instruct": 31,
    "Qwen/Qwen3-VL-4B-Instruct": 4,
    "Qwen/Qwen3-30B-A3B-Thinking-2507": 31,
    "Qwen/Qwen3-30B-A3B-Instruct-2507": 31,
    "Qwen/Qwen3-4B-Thinking-2507": 4,
    "Qwen/Qwen3-4B-Instruct-2507": 4,
    "Qwen/Qwen3-VL-8B-Instruct": 8,
    "Qwen/Qwen3-VL-4B-Thinking": 4,
    "Qwen/Qwen3-VL-32B-Thinking": 32,
    "Qwen/Qwen3-0.6B": 0.6,
    "Qwen/Qwen3-1.7B": 1.7,
    "Qwen/Qwen3-4B": 4,
    "Qwen/Qwen3-8B": 8,
    "Qwen/Qwen3-VL-8B-Thinking": 8,
    "Qwen/Qwen3-14B": 15,
    "Qwen/Qwen3-32B": 33,
    "Qwen/Qwen2.5-VL-7B-Instruct": 7,
    "Qwen/Qwen2.5-VL-3B-Instruct": 3,
    "Qwen/Qwen2.5-VL-32B-Instruct": 32,
    "Qwen/Qwen2.5-VL-72B-Instruct": 72,
    "Qwen/QVQ-72B-Preview": 72,
    "OpenGVLab/InternVL3_5-38B-Instruct": 38,
    "OpenGVLab/InternVL3_5-14B-Instruct": 15,
    "OpenGVLab/InternVL3_5-8B-Instruct": 8,
    "OpenGVLab/InternVL3_5-4B-Instruct": 5,
    "OpenGVLab/InternVL3_5-2B-Instruct": 2,
    "OpenGVLab/InternVL3_5-1B-Instruct": 1,
    "CohereLabs/command-a-reasoning-08-2025": 111,
    "CohereLabs/c4ai-command-a-03-2025": 111,
}


def is_multimodal_model(model_key: str) -> bool:
    return model_key in MULTIMODAL_MODELS


def is_reasoning_model(model_key: str) -> bool:
    return model_key in REASONING_MODELS


def is_korean_model(model_key: str) -> bool:
    return model_key in KOREAN_MODELS


def is_proprietary_model(model_key: str) -> bool:
    return model_key in PROPRIETARY_MODELS
