metadata:
  release_date: null
  model_size: 88
  context_window: null
  max_output_tokens: null
  modality: "vlm"
  is_reasoning: false
  huggingface_url: "https://huggingface.co/meta-llama/Llama-3.2-90B-Vision-Instruct"

model:
  name: "meta-llama/Llama-3.2-90B-Vision-Instruct"
  client: "local"
  engine: "transformers"
  api_key_env: "EMPTY"
  is_vlm: true
  params:
    max_tokens: null
    temperature: 0.0
    top_p: 0.95

transformers:
  device: "cuda"
